# Generated by Django 5.2.11 on 2026-02-06 13:44

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slider", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slider",
            name="description",
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name="slider",
            name="image",
            field=models.ImageField(upload_to="sliders_images/"),
        ),
    ]
